"""Probe this machine and derive build tuning (spec 2.1, 2.2).

Writes config/hardware.toml and config/tuning.toml. Nothing in BINMAN may
hard-code a core count, a memory figure or a device: every consumer reads
config/tuning.toml. Re-running this on different hardware must be the only
change needed to retune the build.
"""

from __future__ import annotations

import json
import os
import platform
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config"


def sh(cmd: list[str]) -> str:
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=60).stdout.strip()
    except Exception:
        return ""


def sysctl(key: str) -> str:
    return sh(["sysctl", "-n", key])


def as_int(value: str, default: int = 0) -> int:
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return default


def probe_gpu_cores() -> int:
    """GPU core count from system_profiler. Returns 0 when it cannot be read."""
    out = sh(["system_profiler", "SPDisplaysDataType"])
    match = re.search(r"Total Number of Cores:\s*(\d+)", out)
    return as_int(match.group(1)) if match else 0


def probe_chipset() -> str:
    out = sh(["system_profiler", "SPDisplaysDataType"])
    match = re.search(r"Chipset Model:\s*(.+)", out)
    return match.group(1).strip() if match else "unknown"


def probe_disk(path: Path) -> dict:
    usage = shutil.disk_usage(path)
    gb = 1024 ** 3
    return {
        "path": str(path),
        "total_gb": round(usage.total / gb, 1),
        "used_gb": round(usage.used / gb, 1),
        "free_gb": round(usage.free / gb, 1),
    }


def probe_mps() -> dict:
    """torch MPS availability. Absent torch is not a failure: it is a fact."""
    code = (
        "import json, torch;"
        "print(json.dumps({'installed': True, 'version': torch.__version__,"
        " 'available': bool(torch.backends.mps.is_available()),"
        " 'built': bool(torch.backends.mps.is_built())}))"
    )
    out = sh([sys.executable, "-c", code])
    try:
        return json.loads(out)
    except Exception:
        return {"installed": False, "version": None, "available": False, "built": False}


def probe_mlx() -> dict:
    """MLX availability plus the smoke test that decides model_device (spec 2.2, G1)."""
    code = (
        "import json, mlx.core as mx;"
        "a = mx.ones((256, 256)); b = (a @ a); mx.eval(b);"
        "print(json.dumps({'installed': True, 'version': getattr(mx, '__version__', 'unknown'),"
        " 'default_device': str(mx.default_device()),"
        " 'smoke_test': float(b[0, 0].item()) == 256.0}))"
    )
    out = sh([sys.executable, "-c", code])
    try:
        return json.loads(out)
    except Exception:
        return {"installed": False, "version": None, "default_device": None, "smoke_test": False}


def probe_tool_versions() -> dict:
    """Record what the geometry path will actually run, for provenance."""
    probes = {
        "gemmi": [sys.executable, "-c", "import gemmi; print(gemmi.__version__)"],
        # freesasa exposes no __version__; take it from package metadata instead.
        "freesasa": [sys.executable, "-c",
                     "from importlib.metadata import version; print(version('freesasa'))"],
        "biotite": [sys.executable, "-c", "import biotite; print(biotite.__version__)"],
        "rdkit": [sys.executable, "-c", "import rdkit; print(rdkit.__version__)"],
        "mkdssp": ["mkdssp", "--version"],
        "fpocket": ["fpocket", "-h"],
        "obabel": ["obabel", "-V"],
        "java": ["java", "-version"],
    }
    found = {}
    for name, cmd in probes.items():
        if shutil.which(cmd[0]) is None:
            found[name] = None
            continue
        out = sh(cmd) or sh(cmd[:1])
        found[name] = (out.splitlines()[0].strip() if out else "present")
    return found


def toml_escape(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def emit_toml(data: dict, title: str) -> str:
    """Minimal TOML writer: tables one level deep, which is all these files need."""
    lines = [f"# {title}", f"# Generated by tools/hwprobe.py at {data['_generated_at']}",
             "# Do not edit by hand: re-run `pixi run hwprobe` instead.", ""]
    for table, body in data.items():
        if table.startswith("_"):
            continue
        lines.append(f"[{table}]")
        for key, value in body.items():
            if isinstance(value, bool):
                lines.append(f"{key} = {str(value).lower()}")
            elif isinstance(value, (int, float)):
                lines.append(f"{key} = {value}")
            elif value is None:
                lines.append(f'{key} = "unavailable"')
            elif isinstance(value, list):
                inner = ", ".join(f'"{toml_escape(v)}"' for v in value)
                lines.append(f"{key} = [{inner}]")
            else:
                lines.append(f'{key} = "{toml_escape(value)}"')
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    gb = 1024 ** 3

    perf_cores = as_int(sysctl("hw.perflevel0.physicalcpu"))
    eff_cores = as_int(sysctl("hw.perflevel1.physicalcpu"))
    physical = as_int(sysctl("hw.physicalcpu"), perf_cores + eff_cores)
    logical = as_int(sysctl("hw.logicalcpu"), physical)
    memory_bytes = as_int(sysctl("hw.memsize"))
    memory_gb = round(memory_bytes / gb, 1)

    # A machine that reports no perflevel split (Intel, or a VM) still needs a
    # sane worker count, so fall back to the physical core count.
    effective_perf = perf_cores or physical or os.cpu_count() or 4

    mps = probe_mps()
    mlx = probe_mlx()
    disk = probe_disk(ROOT)

    hardware = {
        "_generated_at": now,
        "host": {
            "chip": sysctl("machdep.cpu.brand_string") or platform.processor() or "unknown",
            "gpu_chipset": probe_chipset(),
            "gpu_cores": probe_gpu_cores(),
            "machine": platform.machine(),
            "os": f"{platform.system()} {platform.release()}",
            "python": platform.python_version(),
            "python_executable": sys.executable,
            "hostname": platform.node(),
        },
        "cpu": {
            "performance_cores": perf_cores,
            "efficiency_cores": eff_cores,
            "physical_cores": physical,
            "logical_cores": logical,
        },
        "memory": {
            "total_bytes": memory_bytes,
            "total_gb": memory_gb,
        },
        "disk": disk,
        "mps": mps,
        "mlx": mlx,
        "tools": probe_tool_versions(),
    }

    # Spec 2.2: every rule below is derived, never hard-coded.
    cpu_workers = max(2, effective_perf - 2)
    memory_headroom_gb = 24
    model_device = "mps" if mlx.get("smoke_test") else "cpu"

    tuning = {
        "_generated_at": now,
        "compute": {
            "cpu_workers": cpu_workers,
            "io_workers": 16,
            "freesasa_workers": cpu_workers,
            "dssp_workers": cpu_workers,
            "memory_headroom_gb": memory_headroom_gb,
            "usable_memory_gb": round(max(0.0, memory_gb - memory_headroom_gb), 1),
            "max_compute_hours": 96,
        },
        "model": {
            "model_device": model_device,
            "model_instances": 1,
            "mlx_batch_size": 4,
            "mlx_available": bool(mlx.get("installed") and mlx.get("smoke_test")),
            # G1 opens only when MLX fails on MPS *and* CPU (spec gate table).
            "gate_g1_candidate": not bool(mlx.get("installed")),
        },
        "io": {
            "rcsb_rate_limit_per_sec": 8,
            "afdb_rate_limit_per_sec": 8,
            "generic_rate_limit_per_sec": 4,
            "retry_attempts": 5,
            "retry_backoff_seconds": 2,
            "http_timeout_seconds": 60,
        },
        "disk": {
            "gate_g5_free_gb_floor": 50,
            "free_gb_at_probe": disk["free_gb"],
        },
        "env": {
            "PYTORCH_ENABLE_MPS_FALLBACK": "1",
            "TOKENIZERS_PARALLELISM": "false",
            "OMP_NUM_THREADS": str(cpu_workers),
        },
    }

    CONFIG.mkdir(parents=True, exist_ok=True)
    (CONFIG / "hardware.toml").write_text(emit_toml(hardware, "BINMAN hardware probe"))
    (CONFIG / "tuning.toml").write_text(emit_toml(tuning, "BINMAN derived tuning"))
    (CONFIG / "hardware.json").write_text(json.dumps(hardware, indent=2) + "\n")

    print(f"chip                : {hardware['host']['chip']}")
    print(f"gpu                 : {hardware['host']['gpu_chipset']} ({hardware['host']['gpu_cores']} cores)")
    print(f"cores (perf/eff)    : {perf_cores}/{eff_cores}")
    print(f"memory              : {memory_gb} GB")
    print(f"free disk           : {disk['free_gb']} GB")
    print(f"mps available       : {mps.get('available')}")
    print(f"mlx smoke test      : {mlx.get('smoke_test')}  device={mlx.get('default_device')}")
    print(f"cpu_workers         : {cpu_workers}")
    print(f"model_device        : {model_device}")
    print(f"wrote               : config/hardware.toml, config/tuning.toml, config/hardware.json")

    if disk["free_gb"] < tuning["disk"]["gate_g5_free_gb_floor"]:
        print("WARNING: free disk below the G5 floor", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
